---
#- name: Installing virtualbox packages using apt
#  become: true
#  apt:
#    pkg: "virtualbox"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'Ubuntu'

#- name: Installing virtualbox packages using yum
#  become: true
#  yum:
#    pkg: "virtualbox"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


#- name: Installing virtualbox packages using pacman
#  pacman:
#    name: "virtualbox"
#    state: present
#  when: ansible_distribution == 'MacOSX'

- name: Installing virtualbox packages
  become: true
  package:
    name: "virtualbox"
    state: present
